/*
  Warnings:

  - The values [BILL_OF_LADING,AIRWAY_BILL,IMPORT_DECLARATION,CUSTOMS_CLEARANCE,PAYMENT_RECEIPT] on the enum `DocumentType` will be removed. If these variants are still used in the database, this will fail.
  - The values [APPROVED,REJECTED,ACTIVE,CLOSED] on the enum `LCStatus` will be removed. If these variants are still used in the database, this will fail.
  - The values [CUSTOMS_CHECK,RELEASED,ARRIVED] on the enum `ShipmentEventType` will be removed. If these variants are still used in the database, this will fail.
  - The values [IN_TRANSIT,CUSTOMS_HOLD,CLEARED,DELIVERED] on the enum `ShipmentStatus` will be removed. If these variants are still used in the database, this will fail.

*/
-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('DRAFT', 'PENDING_REVIEW', 'APPROVED', 'REJECTED', 'SUBMITTED', 'VERIFIED', 'ARCHIVED');

-- AlterEnum
BEGIN;
CREATE TYPE "DocumentType_new" AS ENUM ('COMMERCIAL_INVOICE', 'PROFORMA_INVOICE', 'PACKING_LIST', 'WEIGHT_LIST', 'MEASUREMENT_LIST', 'SALES_CONTRACT', 'PURCHASE_ORDER', 'ORDER_CONFIRMATION', 'SHIPPING_INSTRUCTIONS', 'SHIPPING_ADVICE', 'QUOTATION', 'INDENT', 'PERFORMA_STATEMENT', 'CERTIFICATE_OF_VALUE', 'INSPECTION_CERTIFICATE_COMMERCIAL', 'BILL_OF_LADING_ORIGINAL', 'BILL_OF_LADING_SEAWAY', 'SWITCH_BILL_OF_LADING', 'CHARTER_PARTY_BILL_OF_LADING', 'MATES_RECEIPT', 'DOCK_RECEIPT', 'DELIVERY_ORDER', 'CARGO_MANIFEST', 'FREIGHT_MANIFEST', 'STOWAGE_PLAN', 'SHIPPING_ORDER', 'AIR_WAYBILL', 'HOUSE_AIR_WAYBILL', 'MASTER_AIR_WAYBILL', 'AIR_CARGO_MANIFEST', 'AIR_CONSIGNMENT_NOTE', 'CMR_CONSIGNMENT_NOTE', 'TRUCK_WAYBILL', 'RAILWAY_RECEIPT', 'ROAD_CONSIGNMENT_NOTE', 'TRANSIT_WAYBILL', 'MULTIMODAL_TRANSPORT_DOCUMENT', 'COMBINED_TRANSPORT_BILL_OF_LADING', 'FIATA_BILL_OF_LADING', 'WAREHOUSE_RECEIPT', 'STORAGE_RECEIPT', 'GATE_PASS', 'CARTING_ORDER', 'CART_TICKET', 'LOADING_LIST', 'UNLOADING_REPORT', 'SHIPPING_BILL', 'BILL_OF_EXPORT', 'EXPORT_DECLARATION_FORM', 'ARE_1_ARE_3', 'EXPORT_LICENSE', 'DUTY_DRAWBACK_CLAIM_FORM', 'EXPORT_GENERAL_MANIFEST', 'BILL_OF_ENTRY', 'IMPORT_LICENSE', 'CUSTOMS_DECLARATION', 'ENTRY_SUMMARY_DECLARATION', 'IMPORT_GENERAL_MANIFEST', 'TRANSIT_DECLARATION', 'SINGLE_ADMINISTRATIVE_DOCUMENT', 'EEI_AES_FILING', 'AES_ITN_NUMBER', 'LET_EXPORT_ORDER', 'ECCN_CLASSIFICATION', 'SHIPPERS_LETTER_OF_INSTRUCTION', 'EXPORT_DECLARATION', 'LC_ASSIGNMENT', 'LETTER_OF_CREDIT', 'STANDBY_LETTER_OF_CREDIT', 'BILL_OF_EXCHANGE', 'PROMISSORY_NOTE', 'BANK_DRAFT', 'BANK_REALISATION_CERTIFICATE', 'EBRC', 'FIRC', 'COLLECTION_ORDER', 'CREDIT_ADVICE', 'DEBIT_ADVICE', 'PACKING_CREDIT_DOCUMENTS', 'POST_SHIPMENT_FINANCE_DOCUMENTS', 'NEGOTIATION_DOCUMENTS', 'REMITTANCE_APPLICATION', 'SWIFT_MESSAGE_COPY', 'LC_APPLICATION', 'LC_SWIFT_MT700', 'LC_ADVICE_LETTER', 'LC_UTILIZATION_CERTIFICATE', 'LOAN_AGREEMENT', 'LOAN_SANCTION_LETTER', 'LOAN_REPAYMENT_CONFIRMATION', 'LOAN_CLOSURE_CERTIFICATE', 'INSURANCE_POLICY', 'INSURANCE_CERTIFICATE', 'COVER_NOTE', 'MARINE_INSURANCE_POLICY', 'CARGO_INSURANCE_CERTIFICATE', 'OPEN_POLICY_DECLARATION', 'INSURANCE_CLAIM_FORM', 'SURVEY_REPORT', 'LOSS_DAMAGE_CERTIFICATE', 'INSPECTION_CERTIFICATE', 'PRE_SHIPMENT_INSPECTION_CERTIFICATE', 'QUALITY_CERTIFICATE', 'QUANTITY_CERTIFICATE', 'TEST_CERTIFICATE', 'ANALYSIS_CERTIFICATE', 'PHYTOSANITARY_CERTIFICATE', 'FUMIGATION_CERTIFICATE', 'HEALTH_CERTIFICATE', 'SANITARY_CERTIFICATE', 'CERTIFICATE_OF_ORIGIN', 'PREFERENTIAL_CERTIFICATE_OF_ORIGIN', 'NON_PREFERENTIAL_CERTIFICATE_OF_ORIGIN', 'GSP_CERTIFICATE', 'EUR_1_CERTIFICATE', 'FORM_A', 'ATR_CERTIFICATE', 'REX_STATEMENT', 'CHAMBER_OF_COMMERCE_CERTIFICATE', 'DRUG_LICENSE', 'PHARMACEUTICAL_CERTIFICATE', 'FREE_SALE_CERTIFICATE', 'CE_CERTIFICATE', 'FDA_CERTIFICATE', 'MSDS', 'DANGEROUS_GOODS_DECLARATION', 'IMDG_CERTIFICATE', 'HAZARDOUS_CARGO_DECLARATION', 'RADIATION_CERTIFICATE', 'ORGANIC_CERTIFICATE', 'HALAL_CERTIFICATE', 'KOSHER_CERTIFICATE', 'TEXTILE_DECLARATION', 'WOOD_PACKAGING_CERTIFICATE', 'GST_INVOICE', 'GST_REFUND_DOCUMENTS', 'DUTY_DRAWBACK_DOCUMENTS', 'ADVANCE_AUTHORIZATION_DOCUMENTS', 'BOND_LUT', 'EXCISE_CLEARANCE_CERTIFICATE', 'VAT_DOCUMENTS', 'TAX_INVOICE', 'DUTY_PAYMENT_CHALLAN', 'ASSESSMENT_ORDER', 'OUT_OF_CHARGE_ORDER', 'IMPORT_LICENSE_IEC', 'GSTR_2B_ITC_CLAIM', 'FEMA_A2_FORM', 'FREIGHT_INVOICE', 'FREIGHT_QUOTATION', 'BOOKING_CONFIRMATION', 'CONTAINER_RELEASE_ORDER', 'CONTAINER_LOAD_PLAN', 'STUFFING_REPORT', 'DE_STUFFING_REPORT', 'EQUIPMENT_INTERCHANGE_RECEIPT', 'CONTAINER_INSPECTION_REPORT', 'DEMURRAGE_INVOICE', 'DETENTION_INVOICE', 'BROKER_MANDATE', 'INCOTERMS_SHEET', 'HS_CODE_CLASSIFICATION', 'E_INVOICE', 'E_WAY_BILL', 'E_BILL_OF_LADING', 'DIGITAL_CERTIFICATE_OF_ORIGIN', 'BLOCKCHAIN_BILL_OF_LADING', 'ELECTRONIC_DATA_INTERCHANGE_FILING', 'CUSTOMS_E_FILING_DOCUMENTS', 'PORT_COMMUNITY_SYSTEM_DOCUMENTS', 'NOTICE_OF_CLAIM', 'LETTER_OF_PROTEST', 'ARBITRATION_DOCUMENTS', 'LEGAL_NOTICE', 'SETTLEMENT_AGREEMENT', 'DISPUTE_RESOLUTION_DOCUMENTS', 'OTHER');
ALTER TABLE "Document" ALTER COLUMN "type" TYPE "DocumentType_new" USING ("type"::text::"DocumentType_new");
ALTER TYPE "DocumentType" RENAME TO "DocumentType_old";
ALTER TYPE "DocumentType_new" RENAME TO "DocumentType";
DROP TYPE "public"."DocumentType_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "LCStatus_new" AS ENUM ('DRAFT', 'APPLIED', 'ISSUED', 'ADVISED', 'CONFIRMED', 'DOCUMENTS_SUBMITTED', 'DOCUMENTS_ACCEPTED', 'DOCUMENTS_DISCREPANT', 'PAID', 'RETIRED', 'EXPIRED', 'CANCELLED');
ALTER TABLE "public"."LC" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "LC" ALTER COLUMN "status" TYPE "LCStatus_new" USING ("status"::text::"LCStatus_new");
ALTER TYPE "LCStatus" RENAME TO "LCStatus_old";
ALTER TYPE "LCStatus_new" RENAME TO "LCStatus";
DROP TYPE "public"."LCStatus_old";
ALTER TABLE "LC" ALTER COLUMN "status" SET DEFAULT 'APPLIED';
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "ShipmentEventType_new" AS ENUM ('BOOKED', 'CARGO_RECEIVED', 'LOADED', 'DEPARTED', 'IN_TRANSIT', 'ARRIVED_PORT', 'DISCHARGED', 'AT_CFS', 'CUSTOMS_HOLD', 'DOCUMENT_VERIFIED', 'CUSTOMS_CLEARED', 'OUT_FOR_DELIVERY', 'DELIVERED', 'DELAYED', 'EXCEPTION');
ALTER TABLE "ShipmentEvent" ALTER COLUMN "type" TYPE "ShipmentEventType_new" USING ("type"::text::"ShipmentEventType_new");
ALTER TYPE "ShipmentEventType" RENAME TO "ShipmentEventType_old";
ALTER TYPE "ShipmentEventType_new" RENAME TO "ShipmentEventType";
DROP TYPE "public"."ShipmentEventType_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "ShipmentStatus_new" AS ENUM ('CREATED', 'COMPLETED');
ALTER TABLE "public"."Shipment" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "Shipment" ALTER COLUMN "status" TYPE "ShipmentStatus_new" USING ("status"::text::"ShipmentStatus_new");
ALTER TYPE "ShipmentStatus" RENAME TO "ShipmentStatus_old";
ALTER TYPE "ShipmentStatus_new" RENAME TO "ShipmentStatus";
DROP TYPE "public"."ShipmentStatus_old";
ALTER TABLE "Shipment" ALTER COLUMN "status" SET DEFAULT 'CREATED';
COMMIT;
