const PRICING = {
  EXPORTER: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 39,
      priceAnnual: 390,
      description:
        "For small exporters managing limited international shipments",
      features: [
        { text: "Up to 10 shipments per month", included: true },
        { text: "Standard export document templates", included: true },
        { text: "Basic shipment tracking", included: true },
        { text: "1 user account", included: true },
        { text: "Basic compliance screening", included: true },
        { text: "Email support", included: true },
        { text: "Advanced document automation", included: false },
        { text: "Trade analytics dashboard", included: false },
        { text: "Multi-user collaboration", included: false },
        { text: "API access", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 119,
      priceAnnual: 1190,
      description: "For growing exporters handling larger trade volumes",
      features: [
        { text: "Up to 100 shipments per month", included: true },
        { text: "Advanced document automation", included: true },
        { text: "Multi-user collaboration (10 users)", included: true },
        { text: "Trade analytics dashboards", included: true },
        { text: "Priority support", included: true },
        { text: "API access", included: true },
        { text: "Compliance risk alerts", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Workflow automation", included: true },
        { text: "Custom integrations", included: false },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description: "For multinational exporters with complex supply chains",
      features: [
        { text: "Unlimited shipments", included: true },
        { text: "Unlimited users", included: true },
        { text: "Custom integrations & APIs", included: true },
        { text: "Dedicated account manager", included: true },
        { text: "Advanced trade intelligence analytics", included: true },
        { text: "Custom workflow automation", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "SLA uptime guarantee", included: true },
        { text: "Audit logs & compliance reporting", included: true },
        { text: "Enterprise security controls", included: true },
      ],
    },
  ],

  IMPORTER: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 39,
      priceAnnual: 390,
      description: "For companies importing goods in smaller volumes",
      features: [
        { text: "Up to 10 import shipments per month", included: true },
        { text: "Import documentation templates", included: true },
        { text: "Shipment tracking", included: true },
        { text: "Duty & tax estimation", included: true },
        { text: "1 user account", included: true },
        { text: "Email support", included: true },
        { text: "Advanced cost analytics", included: false },
        { text: "Supplier collaboration tools", included: false },
        { text: "Multi-user access", included: false },
        { text: "API access", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 119,
      priceAnnual: 1190,
      description: "For businesses managing frequent global imports",
      features: [
        { text: "Up to 100 import shipments per month", included: true },
        { text: "Supplier collaboration workspace", included: true },
        { text: "Advanced cost & duty analytics", included: true },
        { text: "Multi-user collaboration (10 users)", included: true },
        { text: "Priority support", included: true },
        { text: "Full shipment visibility dashboard", included: true },
        { text: "API access", included: true },
        { text: "Workflow automation", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Custom integrations", included: false },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description: "For global procurement and supply chain teams",
      features: [
        { text: "Unlimited shipments", included: true },
        { text: "Unlimited users", included: true },
        { text: "Advanced supplier intelligence analytics", included: true },
        { text: "Dedicated account manager", included: true },
        { text: "Custom ERP integrations", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "Compliance monitoring automation", included: true },
        { text: "Audit logs", included: true },
        { text: "Custom workflow automation", included: true },
        { text: "Enterprise SLA", included: true },
      ],
    },
  ],

  BROKER: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 49,
      priceAnnual: 490,
      description: "For independent customs brokers managing limited clients",
      features: [
        { text: "Up to 25 declarations per month", included: true },
        { text: "Customs documentation tools", included: true },
        { text: "Basic compliance screening", included: true },
        { text: "Client shipment tracking", included: true },
        { text: "1 user account", included: true },
        { text: "Email support", included: true },
        { text: "Multi-client dashboards", included: false },
        { text: "Workflow automation", included: false },
        { text: "API access", included: false },
        { text: "Advanced compliance engine", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 149,
      priceAnnual: 1490,
      description: "For brokerage firms managing multiple trade clients",
      features: [
        { text: "Up to 300 declarations per month", included: true },
        { text: "Multi-client management dashboard", included: true },
        { text: "Automated customs workflows", included: true },
        { text: "Multi-user collaboration", included: true },
        { text: "Priority support", included: true },
        { text: "Advanced compliance engine", included: true },
        { text: "API integrations", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Trade analytics", included: true },
        { text: "Custom integrations", included: false },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description: "For large brokerage firms and compliance providers",
      features: [
        { text: "Unlimited declarations", included: true },
        { text: "Unlimited clients", included: true },
        { text: "Enterprise compliance automation", included: true },
        { text: "Dedicated success manager", included: true },
        { text: "Custom regulatory integrations", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "Audit trails", included: true },
        { text: "Enterprise analytics", included: true },
        { text: "Custom workflows", included: true },
        { text: "SLA guarantee", included: true },
      ],
    },
  ],

  LOGISTICS_PROVIDER: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 49,
      priceAnnual: 490,
      description: "For small logistics operators managing shipments",
      features: [
        { text: "Up to 50 shipments tracked", included: true },
        { text: "Shipment tracking dashboard", included: true },
        { text: "Basic route analytics", included: true },
        { text: "Client shipment updates", included: true },
        { text: "1 user account", included: true },
        { text: "Email support", included: true },
        { text: "Fleet analytics", included: false },
        { text: "Multi-user collaboration", included: false },
        { text: "API integrations", included: false },
        { text: "Advanced logistics automation", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 149,
      priceAnnual: 1490,
      description: "For logistics firms managing high shipment volumes",
      features: [
        { text: "Up to 1000 shipments tracked", included: true },
        { text: "Fleet analytics dashboard", included: true },
        { text: "Multi-user collaboration", included: true },
        { text: "Client shipment collaboration workspace", included: true },
        { text: "Priority support", included: true },
        { text: "API access", included: true },
        { text: "Workflow automation", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Advanced route optimization", included: true },
        { text: "Custom integrations", included: false },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description: "For global logistics networks and freight forwarders",
      features: [
        { text: "Unlimited shipments", included: true },
        { text: "Unlimited users", included: true },
        { text: "Advanced logistics AI analytics", included: true },
        { text: "Custom system integrations", included: true },
        { text: "Dedicated account manager", included: true },
        { text: "Enterprise automation engine", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "Real-time global shipment intelligence", included: true },
        { text: "Audit logs", included: true },
        { text: "SLA guarantee", included: true },
      ],
    },
  ],
  BANK: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 199,
      priceAnnual: 1990,
      description:
        "For small financial institutions facilitating trade finance",
      features: [
        {
          text: "Up to 50 trade finance transactions per month",
          included: true,
        },
        { text: "Basic trade document verification", included: true },
        { text: "Letter of Credit document management", included: true },
        { text: "Compliance screening tools", included: true },
        { text: "1 user account", included: true },
        { text: "Email support", included: true },
        { text: "Trade finance analytics", included: false },
        { text: "Multi-user collaboration", included: false },
        { text: "API access", included: false },
        { text: "Automated compliance engine", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 499,
      priceAnnual: 4990,
      description:
        "For banks actively financing international trade operations",
      features: [
        {
          text: "Up to 500 trade finance transactions per month",
          included: true,
        },
        { text: "Advanced trade document verification", included: true },
        { text: "Automated Letter of Credit processing", included: true },
        { text: "Multi-user collaboration (20 users)", included: true },
        { text: "Priority support", included: true },
        { text: "Trade finance analytics dashboard", included: true },
        { text: "Compliance risk alerts", included: true },
        { text: "API access", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Workflow automation", included: true },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description: "For global banks managing complex trade finance networks",
      features: [
        { text: "Unlimited trade finance transactions", included: true },
        { text: "Unlimited users", included: true },
        { text: "Advanced compliance automation", included: true },
        { text: "Custom core banking integrations", included: true },
        { text: "Dedicated success manager", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "Enterprise risk analytics", included: true },
        { text: "Audit trails & regulatory reporting", included: true },
        { text: "Custom workflow automation", included: true },
        { text: "Enterprise SLA guarantee", included: true },
      ],
    },
  ],

  CUSTOMS: [
    {
      id: "basic",
      name: "Basic",
      priceMonthly: 149,
      priceAnnual: 1490,
      description:
        "For small customs clearance teams managing limited declarations",
      features: [
        { text: "Up to 200 customs declarations per month", included: true },
        { text: "Basic customs documentation tools", included: true },
        { text: "HS code lookup tools", included: true },
        { text: "Shipment verification tools", included: true },
        { text: "1 user account", included: true },
        { text: "Email support", included: true },
        { text: "Advanced compliance analytics", included: false },
        { text: "Multi-user access", included: false },
        { text: "API access", included: false },
        { text: "Automated declaration processing", included: false },
      ],
    },
    {
      id: "pro",
      name: "Pro",
      featured: true,
      priceMonthly: 399,
      priceAnnual: 3990,
      description:
        "For customs authorities and clearance firms managing high declaration volumes",
      features: [
        { text: "Up to 3000 customs declarations per month", included: true },
        { text: "Automated declaration processing", included: true },
        { text: "Multi-user collaboration (20 users)", included: true },
        { text: "Compliance analytics dashboard", included: true },
        { text: "Priority support", included: true },
        { text: "API integrations", included: true },
        { text: "Risk detection alerts", included: true },
        { text: "AI Trade Copilot (basic)", included: true },
        { text: "Advanced HS code intelligence", included: true },
        { text: "Workflow automation", included: true },
      ],
    },
    {
      id: "enterprise",
      name: "Enterprise",
      priceMonthly: null,
      priceAnnual: null,
      description:
        "For national customs authorities and large clearance networks",
      features: [
        { text: "Unlimited declarations", included: true },
        { text: "Unlimited users", included: true },
        { text: "Government-grade compliance systems", included: true },
        { text: "Custom regulatory integrations", included: true },
        { text: "Dedicated infrastructure support", included: true },
        { text: "AI Trade Copilot (advanced)", included: true },
        { text: "Enterprise analytics", included: true },
        { text: "Audit logs & regulatory reporting", included: true },
        { text: "Custom workflow automation", included: true },
        { text: "SLA guarantee", included: true },
      ],
    },
  ],
};

export default PRICING