import { CheckCircle2 } from "lucide-react";
import { ClockIcon } from "lucide-react";
import { ArrowRightCircle } from "lucide-react";
import { PauseCircle } from "lucide-react";

export const SHIPMENTS = [
  {
    id: "SHP-2024-001",
    origin: "Mumbai",
    destination: "Rotterdam",
    status: "In Transit",
    carrier: "Maersk",
    eta: "Mar 18, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-002",
    origin: "Shanghai",
    destination: "Los Angeles",
    status: "Customs Hold",
    carrier: "COSCO",
    eta: "Mar 15, 2026",
    docs: 12,
  },
  {
    id: "SHP-2024-003",
    origin: "Hamburg",
    destination: "São Paulo",
    status: "Delivered",
    carrier: "Hapag-Lloyd",
    eta: "Mar 10, 2026",
    docs: 10,
  },
  {
    id: "SHP-2024-004",
    origin: "Singapore",
    destination: "Dubai",
    status: "In Transit",
    carrier: "MSC",
    eta: "Mar 22, 2026",
    docs: 6,
  },
  {
    id: "SHP-2024-005",
    origin: "Tokyo",
    destination: "Sydney",
    status: "Pending",
    carrier: "ONE",
    eta: "Mar 25, 2026",
    docs: 4,
  },
  {
    id: "SHP-2024-006",
    origin: "New York",
    destination: "London",
    status: "In Transit",
    carrier: "CMA CGM",
    eta: "Mar 20, 2026",
    docs: 9,
  },
  {
    id: "SHP-2024-007",
    origin: "Busan",
    destination: "Vancouver",
    status: "In Transit",
    carrier: "Evergreen",
    eta: "Mar 28, 2026",
    docs: 7,
  },
  {
    id: "SHP-2024-008",
    origin: "Chennai",
    destination: "Antwerp",
    status: "Pending",
    carrier: "ZIM",
    eta: "Apr 02, 2026",
    docs: 3,
  },
  {
    id: "SHP-2024-009",
    origin: "Shenzhen",
    destination: "Hamburg",
    status: "Delivered",
    carrier: "Maersk",
    eta: "Mar 08, 2026",
    docs: 11,
  },
  {
    id: "SHP-2024-010",
    origin: "Jeddah",
    destination: "Mumbai",
    status: "Customs Hold",
    carrier: "MSC",
    eta: "Mar 16, 2026",
    docs: 5,
  },
  {
    id: "SHP-2024-011",
    origin: "Los Angeles",
    destination: "Tokyo",
    status: "In Transit",
    carrier: "ONE",
    eta: "Mar 30, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-012",
    origin: "Rotterdam",
    destination: "Singapore",
    status: "Pending",
    carrier: "Hapag-Lloyd",
    eta: "Apr 05, 2026",
    docs: 2,
  },
  {
    id: "SHP-2024-013",
    origin: "Mumbai",
    destination: "Rotterdam",
    status: "In Transit",
    carrier: "Maersk",
    eta: "Mar 18, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-014",
    origin: "Shanghai",
    destination: "Los Angeles",
    status: "Customs Hold",
    carrier: "COSCO",
    eta: "Mar 15, 2026",
    docs: 12,
  },
  {
    id: "SHP-2024-015",
    origin: "Hamburg",
    destination: "São Paulo",
    status: "Delivered",
    carrier: "Hapag-Lloyd",
    eta: "Mar 10, 2026",
    docs: 10,
  },
  {
    id: "SHP-2024-016",
    origin: "Singapore",
    destination: "Dubai",
    status: "In Transit",
    carrier: "MSC",
    eta: "Mar 22, 2026",
    docs: 6,
  },
  {
    id: "SHP-2024-017",
    origin: "Tokyo",
    destination: "Sydney",
    status: "Pending",
    carrier: "ONE",
    eta: "Mar 25, 2026",
    docs: 4,
  },
  {
    id: "SHP-2024-018",
    origin: "New York",
    destination: "London",
    status: "In Transit",
    carrier: "CMA CGM",
    eta: "Mar 20, 2026",
    docs: 9,
  },
  {
    id: "SHP-2024-019",
    origin: "Busan",
    destination: "Vancouver",
    status: "In Transit",
    carrier: "Evergreen",
    eta: "Mar 28, 2026",
    docs: 7,
  },
  {
    id: "SHP-2024-020",
    origin: "Chennai",
    destination: "Antwerp",
    status: "Pending",
    carrier: "ZIM",
    eta: "Apr 02, 2026",
    docs: 3,
  },
  {
    id: "SHP-2024-021",
    origin: "Shenzhen",
    destination: "Hamburg",
    status: "Delivered",
    carrier: "Maersk",
    eta: "Mar 08, 2026",
    docs: 11,
  },
  {
    id: "SHP-2024-022",
    origin: "Jeddah",
    destination: "Mumbai",
    status: "Customs Hold",
    carrier: "MSC",
    eta: "Mar 16, 2026",
    docs: 5,
  },
  {
    id: "SHP-2024-023",
    origin: "Los Angeles",
    destination: "Tokyo",
    status: "In Transit",
    carrier: "ONE",
    eta: "Mar 30, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-024",
    origin: "Rotterdam",
    destination: "Singapore",
    status: "Pending",
    carrier: "Hapag-Lloyd",
    eta: "Apr 05, 2026",
    docs: 2,
  },
  {
    id: "SHP-2024-025",
    origin: "Mumbai",
    destination: "Rotterdam",
    status: "In Transit",
    carrier: "Maersk",
    eta: "Mar 18, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-026",
    origin: "Shanghai",
    destination: "Los Angeles",
    status: "Customs Hold",
    carrier: "COSCO",
    eta: "Mar 15, 2026",
    docs: 12,
  },
  {
    id: "SHP-2024-027",
    origin: "Hamburg",
    destination: "São Paulo",
    status: "Delivered",
    carrier: "Hapag-Lloyd",
    eta: "Mar 10, 2026",
    docs: 10,
  },
  {
    id: "SHP-2024-028",
    origin: "Singapore",
    destination: "Dubai",
    status: "In Transit",
    carrier: "MSC",
    eta: "Mar 22, 2026",
    docs: 6,
  },
  {
    id: "SHP-2024-029",
    origin: "Tokyo",
    destination: "Sydney",
    status: "Pending",
    carrier: "ONE",
    eta: "Mar 25, 2026",
    docs: 4,
  },
  {
    id: "SHP-2024-030",
    origin: "New York",
    destination: "London",
    status: "In Transit",
    carrier: "CMA CGM",
    eta: "Mar 20, 2026",
    docs: 9,
  },
  {
    id: "SHP-2024-031",
    origin: "Busan",
    destination: "Vancouver",
    status: "In Transit",
    carrier: "Evergreen",
    eta: "Mar 28, 2026",
    docs: 7,
  },
  {
    id: "SHP-2024-032",
    origin: "Chennai",
    destination: "Antwerp",
    status: "Pending",
    carrier: "ZIM",
    eta: "Apr 02, 2026",
    docs: 3,
  },
  {
    id: "SHP-2024-033",
    origin: "Shenzhen",
    destination: "Hamburg",
    status: "Delivered",
    carrier: "Maersk",
    eta: "Mar 08, 2026",
    docs: 11,
  },
  {
    id: "SHP-2024-034",
    origin: "Jeddah",
    destination: "Mumbai",
    status: "Customs Hold",
    carrier: "MSC",
    eta: "Mar 16, 2026",
    docs: 5,
  },
  {
    id: "SHP-2024-035",
    origin: "Los Angeles",
    destination: "Tokyo",
    status: "In Transit",
    carrier: "ONE",
    eta: "Mar 30, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-036",
    origin: "Rotterdam",
    destination: "Singapore",
    status: "Pending",
    carrier: "Hapag-Lloyd",
    eta: "Apr 05, 2026",
    docs: 2,
  },
  {
    id: "SHP-2024-037",
    origin: "Mumbai",
    destination: "Rotterdam",
    status: "In Transit",
    carrier: "Maersk",
    eta: "Mar 18, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-038",
    origin: "Shanghai",
    destination: "Los Angeles",
    status: "Customs Hold",
    carrier: "COSCO",
    eta: "Mar 15, 2026",
    docs: 12,
  },
  {
    id: "SHP-2024-039",
    origin: "Hamburg",
    destination: "São Paulo",
    status: "Delivered",
    carrier: "Hapag-Lloyd",
    eta: "Mar 10, 2026",
    docs: 10,
  },
  {
    id: "SHP-2024-040",
    origin: "Singapore",
    destination: "Dubai",
    status: "In Transit",
    carrier: "MSC",
    eta: "Mar 22, 2026",
    docs: 6,
  },
  {
    id: "SHP-2024-041",
    origin: "Tokyo",
    destination: "Sydney",
    status: "Pending",
    carrier: "ONE",
    eta: "Mar 25, 2026",
    docs: 4,
  },
  {
    id: "SHP-2024-042",
    origin: "New York",
    destination: "London",
    status: "In Transit",
    carrier: "CMA CGM",
    eta: "Mar 20, 2026",
    docs: 9,
  },
  {
    id: "SHP-2024-043",
    origin: "Busan",
    destination: "Vancouver",
    status: "In Transit",
    carrier: "Evergreen",
    eta: "Mar 28, 2026",
    docs: 7,
  },
  {
    id: "SHP-2024-044",
    origin: "Chennai",
    destination: "Antwerp",
    status: "Pending",
    carrier: "ZIM",
    eta: "Apr 02, 2026",
    docs: 3,
  },
  {
    id: "SHP-2024-045",
    origin: "Shenzhen",
    destination: "Hamburg",
    status: "Delivered",
    carrier: "Maersk",
    eta: "Mar 08, 2026",
    docs: 11,
  },
  {
    id: "SHP-2024-046",
    origin: "Jeddah",
    destination: "Mumbai",
    status: "Customs Hold",
    carrier: "MSC",
    eta: "Mar 16, 2026",
    docs: 5,
  },
  {
    id: "SHP-2024-047",
    origin: "Los Angeles",
    destination: "Tokyo",
    status: "In Transit",
    carrier: "ONE",
    eta: "Mar 30, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-048",
    origin: "Rotterdam",
    destination: "Singapore",
    status: "Pending",
    carrier: "Hapag-Lloyd",
    eta: "Apr 05, 2026",
    docs: 2,
  },
  {
    id: "SHP-2024-049",
    origin: "Mumbai",
    destination: "Rotterdam",
    status: "In Transit",
    carrier: "Maersk",
    eta: "Mar 18, 2026",
    docs: 8,
  },
  {
    id: "SHP-2024-050",
    origin: "Shanghai",
    destination: "Los Angeles",
    status: "Customs Hold",
    carrier: "COSCO",
    eta: "Mar 15, 2026",
    docs: 12,
  },
  {
    id: "SHP-2024-051",
    origin: "Hamburg",
    destination: "São Paulo",
    status: "Delivered",
    carrier: "Hapag-Lloyd",
    eta: "Mar 10, 2026",
    docs: 10,
  },
  {
    id: "SHP-2024-052",
    origin: "Singapore",
    destination: "Dubai",
    status: "In Transit",
    carrier: "MSC",
    eta: "Mar 22, 2026",
    docs: 6,
  },
  {
    id: "SHP-2024-053",
    origin: "Tokyo",
    destination: "Sydney",
    status: "Pending",
    carrier: "ONE",
    eta: "Mar 25, 2026",
    docs: 4,
  },
  {
    id: "SHP-2024-054",
    origin: "New York",
    destination: "London",
    status: "In Transit",
    carrier: "CMA CGM",
    eta: "Mar 20, 2026",
    docs: 9,
  },
  {
    id: "SHP-2024-055",
    origin: "Busan",
    destination: "Vancouver",
    status: "In Transit",
    carrier: "Evergreen",
    eta: "Mar 28, 2026",
    docs: 7,
  },
  {
    id: "SHP-2024-056",
    origin: "Chennai",
    destination: "Antwerp",
    status: "Pending",
    carrier: "ZIM",
    eta: "Apr 02, 2026",
    docs: 3,
  },
  {
    id: "SHP-2024-057",
    origin: "Shenzhen",
    destination: "Hamburg",
    status: "Delivered",
    carrier: "Maersk",
    eta: "Mar 08, 2026",
    docs: 11,
  },
  {
    id: "SHP-2024-058",
    origin: "Jeddah",
    destination: "Mumbai",
    status: "Customs Hold",
    carrier: "MSC",
    eta: "Mar 16, 2026",
    docs: 5,
  },
  {
    id: "SHP-2024-059",
    origin: "Los Angeles",
    destination: "Tokyo",
    status: "In Transit",
    carrier: "ONE",
    eta: "Mar 30, 2026",
    docs: 0,
  },
  {
    id: "SHP-2024-060",
    origin: "Rotterdam",
    destination: "Singapore",
    status: "Pending",
    carrier: "Hapag-Lloyd",
    eta: "Apr 05, 2026",
    docs: 2,
  },
];
export const shipmentStatusFilterParams = [
  { id: 4, label: "In Transit", value: "IN_TRANSIT" },
  { id: 8, label: "Customs Hold", value: "CUSTOMS_HOLD" },
  { id: 12, label: "Delivered", value: "DELIVERED" },
  { id: 13, label: "Delayed", value: "DELAYED" },
];

export const shipmentOriginFilterParams = [
  { id: 0, label: "Mumbai", value: "Mumbai" },
  { id: 0, label: "Shanghai", value: "Shanghai" },
  { id: 0, label: "Hamburg", value: "Hamburg" },
  { id: 0, label: "Singapore", value: "Singapore" },
  { id: 0, label: "Tokyo", value: "Tokyo" },
  { id: 0, label: "New York", value: "New York" },
  { id: 0, label: "Chennai", value: "Chennai" },
  { id: 0, label: "Shenzhen", value: "Shenzhen" },
  { id: 0, label: "Jeddah", value: "Jeddah" },
  { id: 0, label: "Los Angeles", value: "Los Angeles" },
  { id: 0, label: "Rotterdam", value: "Rotterdam" },
];

export const statusColor = {
  inTransit: "bg-[#0E1731] text-[#50A2F2] border border-[#1B325B]",
  customsHold: "bg-[#2D0D0E] text-[#F26467] border border-[#571E20]",
  delivered: "bg-[#061E18] text-[#02D492] border border-[#054230]",
  pending: "bg-[#2B1508] text-[#FFB900] border border-[#553606]",
};
;

export const statusIcon = {
  inTransit: ArrowRightCircle,
  customsHold: PauseCircle,
  delivered: CheckCircle2,
  pending: ClockIcon,
};